name: "[04] All Environments: Update application environment variables"

on:  
  push:
    paths:
      - .container-env/conf/**.env
    branches:
      - main

jobs:
  check-envvars-files:
    runs-on: ubuntu-latest
    outputs:
      dev: ${{ steps.filter.outputs.run_dev }}      
      tmp1: ${{ steps.filter.outputs.run_tmp1 }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            tmp:
              - added|modified: '.container-env/conf/website-tmp1.env'
            dev:
              - added|modified: '.container-env/conf/website-dev.env'
            uat:
              - added|modified: '.container-env/conf/website-uat.env'

      - name: tests tmp
        if: steps.filter.outputs.tmp == 'true'
        run: |
           echo "It has changed run sub workflow for tmp"
      
      - name: tests dev
        if: steps.filter.outputs.dev == 'true'
        run: |
           echo "It has changed run sub workflow for dev"

      - name: tests uat
        if: steps.filter.outputs.uat == 'true'
        run: |
           echo "It has changed run sub workflow for uat"
           