name: "[04] All Environments: Update application environment variables"

on:  
  push:
    paths:
      - .container-env/conf/**.env
    branches:
      - 'test-workflow'

jobs:
  check-envvars-files:
    runs-on: ubuntu-latest
    outputs:
      dev: ${{ steps.filter.outputs.run_dev }}      
      tmp1: ${{ steps.filter.outputs.run_tmp1 }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            tmp:
              - added|modified: '.container-env/conf/website-tmp1.env'

      - name: backend tests
        if: steps.filter.outputs.tmp == 'true'
        run: |
           echo "It has changed"
           