name: "[04] All Environments: Update application environment variables"

on:  
  push:
    paths:
      - .container-env/conf/**.env
    branches:
      - 'test-workflow'

jobs:
  check-envvars-files:
    runs-on: ubuntu-latest
    outputs:
      dev: ${{ steps.filter.outputs.run_dev }}      
      tmp1: ${{ steps.filter.outputs.run_tmp1 }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35.5.0
        with:
          path: .container-env/conf
          
      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
            echo "$file was added"
          done